### ISSUE TITLE
Remove transition

### ISSUE THREAD

**Issue by Zer0SkiLL** [daelmaak/ngx-doe-gallery#51]
is there a way to remove the transition? i'd like to display 36 pictures of a car. with the drag of the pictures i could display them as a 360° image, but as long as there is any transition between the pictures, it's not gonna work. any idea?

**Comment by daelmaak** [comment]
Ok so what you mean is that you don't want the pictures to snap into place once you end the drag, is that correct? So they should stay wherever you finished your drag.

**Comment by Zer0SkiLL** [comment]
My idea was zero animation between each picture. fortunately i got another plugin to work from [mediaman ](https://github.com/mediamanDE/angular-three-sixty) that solved my problem. this is no longer an issue for me. Thanks for your reply.

**Comment by daelmaak** [comment]
Ok got you. Turning the animation off would be very easy then. You could use this CSS:
```
doe-gallery::ng-deep doe-viewer ul {
  transition: none;
}
```

**Comment by Zer0SkiLL** [comment]
i wasn't aware of this easy solution, thank you very much!
